version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "${NGINX_PORT}:8000"
        volumes: 
            - .:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql:8.0.31
        container_name: "${CONTAINER_PREFIX}_mysql"
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_docker:latest
        container_name: "${CONTAINER_PREFIX}_php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - .:/var/www/app
        ports: 
            - "${PHP_PORT}:9000"
        networks: 
            - laravel